# Generated by Django 2.1.2 on 2018-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='torre_username',
            field=models.URLField(blank=True),
        ),
    ]
