# Generated by Django 2.1.2 on 2018-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_torre_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='torre_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
